HOST: http://api.extremmy.com/

--- eXtremmy API ---

---
    В случае возникновения любой ошибки ожидается application/json 
    обект с полями error (идентификатор), message (сообщение для логов), 
    userMessage (опциональное сообщение для пользователя).
---

-- 
Виды спорта
--
GET /sports/list
> Accept: application/json
< 200
< Content-Type: application/json
[    
    {
        "ID": 1,
        "name": "Snowboarding / Ski",
        "alias": "snowboarding"
    }
]

-- 
Споты
--

GET /spots/list{?limit,offset}
> Accept: application/json
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 304
+++++
< 503
< Content-Type: application/json
{ 
    "error": 401,
    "message": "Unknown error.",
    "userMessage": "Unknown error. Please try again later."
}
+++++
< 200
< Content-Type: application/json
< Last-Modified: Mon, 3 Jun 2013 00:00:00 GMT
[    
    {
        "ID": 1,
        "name": "Orient Jumping",
        "coordinate": [54.069073,-10.340239],
        "sports": [1,3],
        "rating": 3
    }
]

GET /spots/description/{id}/
> Accept: text/html
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 304
+++++
< 200
< Content-Type: text/html
<p>
   Several paragraphs in light HTML markup 
</p>

GET /spots/events/{id}/{?from,till,limit}
> Accept: application/json
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 200
< Content-Type: application/json
[    
    {
        "ID": 1,
        "name": "Orient Jumping Event",
        "from": 2013-06-06,
        "till": 2013-07-07,
        "spots": [1, 5, 38],
        "sports": [2,4],
        "users": [3, 48, 172],
        "owner": 3,
        "created": 2013-05-05,
    }
]

POST /spots/
> Content-Type: application/json
> Accept: application/json
{ 
    "name": "My new point", 
    "coordinate": [55.990154,37.409945],
    "url": "http://www.extremmy.com",
    "sports": ["skydiving"],
    "rating": 3
}
< 401
< Content-Type: application/json
{ 
    "error": 401,
    "message": "Unauthorized user trying to add spot.",
    "userMessage": "Please sign in."   
}
+++++
< 200
< Content-Type: application/json
{ "ID": 42 }

-- 
Эвенты
--
GET /events/{id}
> Accept: application/json
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 200
< Content-Type: application/json
{
    "ID": 1,
    "name": "Orient Jumping Event",
    "from": 2013-06-06,
    "till": 2013-07-07,
    "spots": [1, 5, 38],
    "sports": ["skydiving", "wakeboarding"],
    "users": [3, 48, 172],
}

GET /events/description/{id}/
> Accept: text/html
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 304
+++++
< 200
< Content-Type: text/html
<p>
   Several paragraphs in light HTML markup 
</p>


GET /events/comments/{id}{?limit,offset}
> Accept: application/json
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 200
< Content-Type: application/json
[
    {
        "ID": 1,
        "text": "Orient Jumping Event",
        "created": "2013-06-06",
        "author": {
            "ID": 1, 
            "username":"UserName"
            },
    }
]